services:

  mysql:
    image: mysql:8.0
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db

    ports:
      - "3306:3306"

  product-service:
    build: .
    image: product-service:1.0
    container_name: product-service

    ports:
      - "8085:8085"

    depends_on:
      - mysql


